version: '3'
networks:
  back:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.2
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
    networks:
     - back
    ports:
      - "2181:2181"


  kafka:
    image: confluentinc/cp-kafka:4.1.2
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

    networks:
      - back
    expose:
      - "9092"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  schema-registry:
    container_name: schema-registry
    image: confluentinc/cp-schema-registry:4.1.2
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: localhost
    networks:
      - back
    expose:
      - "8081"
    ports:
      - "8081:8081"
    depends_on:
      - zookeeper
      - kafka

  kafka-rest:
    container_name: kafka-rest
    image: confluentinc/cp-kafka-rest:4.1.2
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_HOST_NAME: kafka-rest
      KAFKA_REST_LISTENERS: http://kafka-rest:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS: "GET,POST,PUT,OPTIONS"
      KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
    networks:
      - back
    expose:
      - "8082"
    ports:
      - "8082:8082"
    depends_on:
      - zookeeper
      - kafka

  schema-registry-ui:
    container_name: schema-registry-ui
    image: landoop/schema-registry-ui:latest
    environment:
      SCHEMAREGISTRY_URL: http://localhost:8081
    networks:
      - back
    ports:
      - "8001:8000"

  kafka-topic-ui:
    container_name: kafka-topic-ui
    image: landoop/kafka-topics-ui:latest
    environment:
      KAFKA_REST_PROXY_URL: http://localhost:8082
    networks:
      - back
    ports:
      - "8000:8000"
    depends_on:
      - kafka-rest

